server:
  port: 8001
  servlet:
    context-path: /

application:
  #版本号
  version: 1.0.0

dubbo:
  application:
    #应用名称，每个dubbo应用的名称都是唯一的
    name: pay
  registry:
    #注册中心
    address: zookeeper://192.168.1.111:2181
