server:
  port: 8003
  servlet:
    context-path: /

application:
  #版本号
  version: 1.0.0

dubbo:
  application:
    #应用名称，每个dubbo应用的名称都是唯一的
    name: cross
  registry:
    #注册中心
    address: zookeeper://192.168.1.111:2181
  protocol:
    #协议名称
    name: dubbo
    #服务暴露端口
    port: 20880
  scan:
      #扫描服务注册bean
      basePackages: com.internal.playment.cross.impl