server:
  port: @server.cross.port@
  servlet:
    context-path: /

application:
  #版本号
  version: @application.version@

dubbo:
  application:
    #应用名称，每个dubbo应用的名称都是唯一的
    name: cross
  registry:
    #注册中心
    address: @pay.dubbo.registry_addr@
  protocol:
    #协议名称
    name: dubbo
    #服务暴露端口
    port: @dubbo.protocol.cross.port@
  scan:
      #扫描服务注册bean
      basePackages: com.internal.playment.cross.impl