server:
  port: @server.web.agent.port@
  servlet:
    context-path: /

application:
  #版本号
  version: @application.version@

dubbo:
  application:
    #应用名称，每个dubbo应用的名称都是唯一的
    name: agent
  registry:
    #注册中心
    address: @pay.dubbo.registry_addr@
