server:
  port: 8007
  servlet:
    context-path: /

application:
  #版本号
  version: 1.0.0

dubbo:
  application:
    #应用名称，每个dubbo应用的名称都是唯一的
    name: merchant
  registry:
    #注册中心
    address: @pay.dubbo.registry_addr@
